### PR TITLE
Positioning and floating elements 1 st branch

### PR DESCRIPTION
**Pull request by afcastaneda223**
Hi, I had to finish this project alone because my partner had to abandon microverse while we were working on it. I received an email from success telling me to finish the project alone and submit it by myself.

### CODE REVIEW

**Review by Forison — CHANGES_REQUESTED** [review]
Hi Andres👋,
You have done a good job so far, here are changes you have to do to get this project approved🙂
* [ ] Let us rectify the failing linters checks
* [ ] There are few things on the output page you have to address to make it better. below are screenshots of those sections
- navbar section 
Screenshot from 2020-01-09 16-23-43
- - More in Space & Cosmos section
Screenshot from 2020-01-09 16-24-05
Screenshot from 2020-01-09 16-24-48
## That is it KIndly make those changes and submit the project for review
#### Happy coding😇
Addo Forison

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Fantastic job! @afcastaneda223 
There is are only a few things left to do. Virtually all the links on your page are either `<p>` or `<h3>` tags. While they look good, this is not very semantic as they cannot function as links in their current state. Please look into this and make the appropriate changes. 

Take note of all the links on the page, make sure the appropriate tag is used and don't forget to parse your markup through this [validator](https://validator.w3.org/#validate-by-upload) incase there are any errors so you don't end up having to request another review.

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Hello @afcastaneda223 and @FrancisMtambo! :rocket: 
Did you see my comments about the links all over the page and in every section? From what I can see, no visible changes have been made to this effect, however, an additional issue is being presented--Your stickler checks are failing.

Please give a second look to my comments about the links and fix all stickler errors before you request another review! All the best guys :rocket: 


##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Review by nikasulo — APPROVED** [review]
# Great job! @afcastaneda223 
I can see all the hard work you've put into this :medal_military: please do not relent in your subsequent projects! See you at the top :rocket:.

**Pull request merged**
